{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "103b43f3-91d2-44d3-ad1e-f6564491fa5d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-02-14 00:02:04.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.213 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 00:02:04.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import os\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "model_dir = \"model\"\n",
    "\n",
    "models = {\n",
    "    \"Logistic Regression\": joblib.load(os.path.join(model_dir, \"logistic_regression_model.pkl\")),\n",
    "    \"Decision Tree\": joblib.load(os.path.join(model_dir, \"decision_tree_model.pkl\")),\n",
    "    \"KNN\": joblib.load(os.path.join(model_dir, \"knn_model.pkl\")),\n",
    "    \"Naive Bayes\": joblib.load(os.path.join(model_dir, \"naive_bayes_model.pkl\")),\n",
    "    \"Random Forest\": joblib.load(os.path.join(model_dir, \"random_forest_model.pkl\")),\n",
    "    \"XGBoost\": joblib.load(os.path.join(model_dir, \"xgboost_model.pkl\"))\n",
    "}\n",
    "\n",
    "# Load scaler if used during training\n",
    "scaler = joblib.load(os.path.join(model_dir, \"scaler.pkl\")) if os.path.exists(os.path.join(model_dir, \"scaler.pkl\")) else None\n",
    "\n",
    "categorical_columns = ['sex', 'cp', 'restecg', 'exang', 'slope', 'ca', 'thal']\n",
    "label_encoders = {}\n",
    "for col in categorical_columns:\n",
    "    le_path = os.path.join(model_dir, f\"label_encoder_{col}.pkl\")\n",
    "    if os.path.exists(le_path):\n",
    "        label_encoders[col] = joblib.load(le_path)\n",
    "    else:\n",
    "        label_encoders[col] = None\n",
    "\n",
    "st.title(\"Heart Disease Prediction App\")\n",
    "\n",
    "# Upload CSV\n",
    "uploaded_file = st.file_uploader(\"Upload your CSV test data\", type=[\"csv\"])\n",
    "if uploaded_file:\n",
    "    test_df = pd.read_csv(uploaded_file)\n",
    "    st.write(\"Uploaded Test Data:\")\n",
    "    st.dataframe(test_df)\n",
    "\n",
    "# Model selection dropdown\n",
    "model_name = st.selectbox(\"Select a model\", list(models.keys()))\n",
    "\n",
    "def preprocess_input(df):\n",
    "    # Apply label encoding\n",
    "    for col in categorical_columns:\n",
    "        if label_encoders.get(col) is not None and col in df.columns:\n",
    "            df[col] = label_encoders[col].transform(df[col].astype(str))\n",
    "    \n",
    "    # Apply scaler\n",
    "    if scaler:\n",
    "        return scaler.transform(df)\n",
    "    return df.values\n",
    "\n",
    "if uploaded_file and st.button(\"Predict\"):\n",
    "    X_test = preprocess_input(test_df.drop(\"target\", axis=1, errors='ignore'))\n",
    "    y_test = test_df[\"target\"] if \"target\" in test_df.columns else None\n",
    "\n",
    "    model = models[model_name]\n",
    "    y_pred = model.predict(X_test)\n",
    "\n",
    "    st.subheader(f\"Predictions using {model_name}\")\n",
    "    st.write(y_pred)\n",
    "\n",
    "    if y_test is not None:\n",
    "        metrics = {\n",
    "            \"Accuracy\": accuracy_score(y_test, y_pred),\n",
    "            \"Precision\": precision_score(y_test, y_pred),\n",
    "            \"Recall\": recall_score(y_test, y_pred),\n",
    "            \"F1 Score\": f1_score(y_test, y_pred),\n",
    "            \"AUC\": roc_auc_score(y_test, y_pred)\n",
    "        }\n",
    "        st.subheader(\"Evaluation Metrics\")\n",
    "        st.table(metrics)\n",
    "\n",
    "        # Plot confusion matrix\n",
    "        cm = confusion_matrix(y_test, y_pred)\n",
    "        fig, ax = plt.subplots()\n",
    "        sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\",\n",
    "                    xticklabels=[\"Pred 0\", \"Pred 1\"],\n",
    "                    yticklabels=[\"Actual 0\", \"Actual 1\"],\n",
    "                    ax=ax)\n",
    "        st.subheader(\"Confusion Matrix\")\n",
    "        st.pyplot(fig)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "512d1148-4bad-4bcd-95fd-ba7fbb57bb17",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
